import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/comman/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Pet Adoption",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="size-full">
        <div className="size-full flex flex-col">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
